name: Build and run autotests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Install Qt'
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2
          aqtversion: '==3.1.*'

      - name: 'install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            catch2 \
            build-essential \
            libxcb-cursor0 \
            libxcb-xinerama0 \
            libxkbcommon-x11-0 \
            libdbus-1-3 \
            xvfb
      - name: 'Compile application'
        run: |
          qmake CONFIG+=release PREFIX=/usr
          make -j8
          
      - name: 'Compile autotests'
        run: |
          cd tests/auto
          qmake CONFIG+=release
          make -j8

      - name: 'Set up Xvfb'
        run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x16 &
          
      - name: 'Run autotests'
        run: |
            export DISPLAY=:99.0
            cd tests/auto
            ./AutoTests
        
          
